### ISSUE TITLE
DAO doesn't synch

### ISSUE THREAD

**Issue by Tharrso** [bisq-network/bisq#2902]
I just received a bunch of "trade completed" notices and clicked on the buttons to confirm. Then I got an error message something like the DAO could not synch. In the meantime Bisq is open on the Portfolio|Open Trades window and it's still showing my last two trades with the focus flickering back and forth between them. If I try to look at FUNDS or DAO those windows are blank.

**Comment by ghost** [comment]
From time to time, there may be issues with the selected node providing the DAO informations.
Restarting the application (and using another node) is often enough to solve this sync issue.

**Comment by freimair** [comment]
might got fixed by #3112. closed. please feel free to reopen if it happens again.

**Comment by chimp1984** [comment]
No, the issue is not fixed yet. See: https://github.com/bisq-network/bisq/issues/3175
