### ISSUE TITLE
Upgraded to 1.3.0 > “You have locked up funds from a failed trade” for every Trade in Process

### ISSUE THREAD

**Issue by atom-mota** [bisq-network/bisq#4146]
### Description

After I upgraded to v1.3.0 today, I now see this error alert:
“You have locked up funds from a failed trade”
For every trade I have in process.

#### Version

Bisq v1.3.0
Network version: 1; P2P message version: 10; Local DB version: 1; Trade protocol version: 2
Mac OS 10.15.3

### Steps to reproduce

every time I restart, this error pops up for every current trade I have in progress. These are BTC Buy Offers I’ve made or taken, where I’ve sent the Fiat and confirmed > and they’re currently in the “Trade process” step # 3 “Wait for BTC seller’s payment confirmation. 
So I don’t understand why I’m receiving these alerts. 

Every time I restart, these appear again. One alert for each trade, as PDF attached 

### Screenshots

[failed trade alert for trades in progress.pdf](https://github.com/bisq-network/bisq/files/4452271/failed.trade.alert.for.trades.in.progress.pdf)

#### Device or machine
Mac OS X 10.15.3 catalina

#### Additional info
[bisq-logs-after failed alert.txt](https://github.com/bisq-network/bisq/files/4452280/bisq-logs-after.failed.alert.txt)

**Comment by huey735** [comment]
These issues may have been fixed with the latest update v.1.3.1
https://github.com/bisq-network/bisq/releases/tag/v1.3.1

**Comment by atom-mota** [comment]
Hi @huey735 I have successfully upgraded to v1.3.1 but unfortunately, I still see the "You have locked up funds from a failed trade” alerts upon restarting into new version.

**Comment by dextertd** [comment]
I'm in a similar situation but received no popup, but I do get this error message in the logs:

```
[JavaFX Application Thread] WARN  bisq.core.trade.TradeManager: We found a failed trade with locked up funds. That should never happen. trade ID=
```

Presumably we're facing the same issue but my funds are unspent in the deposit address, so it's no a big problem.

However, I do not see my funds in the Locked box in the top-right - but I think they should be there in this scenario?

**Comment by FranciscoTolosa** [comment]
> I'm in a similar situation but received no popup, but I do get this error message in the logs:
> [JavaFX Application Thread] WARN  bisq.core.trade.TradeManager: We found a failed trade with locked up funds. That should never happen. trade ID=
> 
> Presumably we're facing the same issue but my funds are unspent in the deposit address, so it's no a big problem.
> However, I do not see my funds in the Locked box in the top-right - but I think they should be there in this scenario?

I am in the same situation, I have three failed trades after v1.3 and continue after v1.3.1. I also do not see my funds in the Locked box in the top-right.

**Comment by wiz** [comment]
I understand Bisq will release v1.3.2 to address the unfail-trade issue soon
