### ISSUE TITLE
bisq v1.6.5 hanged on shutdown attemp

### ISSUE THREAD

**Issue by bisqubutor** [bisq-network/bisq#5561]
### Description

bisq hangs on shutdown attemp

#### Version

bisq v1.6.5

### Steps to reproduce

close bisq, 

### Expected behaviour

bisq shutdown

### Actual behaviour

nothing happens.

#### Device or machine

x64

#### Additional info

```

.279 [JavaFX Application Thread] INFO  b.c.ClockWatcher: We have been in standby mode for 5831 sec
.285 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: onAwakeFromStandby
.286 [JavaFX Application Thread] INFO  b.c.d.n.l.n.LiteNodeNetworkService: onAwakeFromStandby
.290 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.291 [JavaFX Application Thread] WARN  b.c.p.f.FeeService: We have a pending request open. We ignore that request. httpClient HttpClientImpl{
     socks5ProxyProvider=bisq.network.Socks5ProxyProvider@50ed1c65,
     baseUrl='http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/',
     ignoreSocks5Proxy=false,
     uid='33bafe70-fad4-46f4-8854-5677ec079776',
     connection=null,
     httpclient=null
}
.302 [JavaFX Application Thread] WARN  b.n.p.p.BroadcastHandler: Broadcast did not complete after 120.8 sec.
numPeersForBroadcast=7
numOfCompletedBroadcasts=3
numOfFailedBroadcasts=0
.729 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: Num of latestLivePeers=1
.554 [NetworkNode:SendMessage-to-p2gyooo7hcrkfrdm4hutenbbfn5v4cedbrrcxi56viylm5hu35dhzjqd.onion:9999] INFO  b.n.p.n.NetworkNode: Socket creation to peersNodeAddress p2gyooo7hcrkfrdm4hutenbbfn5v4cedbrrcxi56viylm5hu35dhzjqd.onion:9999 took 1824 ms
.400 [Thread-12] INFO  b.c.a.BisqExecutable: Start graceful shutDown
.406 [Thread-12] INFO  b.c.a.BisqExecutable: OpenOfferManager shutdown started
.407 [Thread-12] INFO  b.c.o.OpenOfferManager: Remove open offers at shutDown. Number of open offers: 0
.407 [Thread-12] INFO  b.c.a.BisqExecutable: OpenOfferManager shutdown completed
.407 [Thread-12] INFO  b.c.b.s.WalletsSetup: walletConfig shutDown started
.418 [ STOPPING] INFO  b.c.b.s.WalletConfig: BtcWallet saved to file
.421 [ STOPPING] INFO  b.c.b.s.WalletConfig: BsqWallet saved to file
.427 [ STOPPING] INFO  b.c.b.s.WalletConfig: SPV file closed
.428 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Stopping ...
.428 [ STOPPING] INFO  o.b.c.PeerGroup: Awaiting PeerGroup shutdown ...
.428 [PeerGroup Thread] ERROR o.b.c.PeerGroup: Exception when shutting down java.lang.IllegalStateException: Expected the service NioClientManager [FAILED] to be TERMINATED, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:329)
	at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitTerminated(AbstractExecutionThreadService.java:223)
	at org.bitcoinj.core.PeerGroup$10.run(PeerGroup.java:1155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

.428 [ STOPPING] INFO  o.b.c.PeerGroup: ... took 1.615 ms
.429 [ STOPPING] INFO  b.c.b.s.WalletConfig: PeerGroup stopped
.429 [Thread-12] INFO  b.c.b.s.WalletsSetup: walletConfig shutDown completed
.429 [Thread-12] INFO  b.c.a.BisqExecutable: WalletsSetup shutdown completed
.430 [Thread-12] INFO  b.n.p.n.TorNetworkNode: Tor has been created already so we can shut it down.
.438 [InputHandler-p2gyooo7hcrkfrdm4hutenbbfn5v4cedbrrcxi56viylm5hu35dhzjqd.onion:9999] WARN  b.n.p.n.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown.
.435 [Thread-12] ERROR b.n.p.n.TorNetworkNode: Shutdown torNetworkNode failed with exception: We did not receive a response within one minute of waiting.

```

**Comment by bisqubutor** [comment]
happened again. last logs:
```

 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerVbyte=27 minFeePerVbyte=2
 [InputHandler-oubgf46wb7n7qntj.onion:9999] WARN  b.n.p.n.Connection: Unknown reason for exception at socket: TorSocket[addr=oubgf46wb7n7qntj.onion,port=9999, localPort=0]
	peer=Optional[oubgf46wb7n7qntj.onion:9999]
	Exception=java.lang.OutOfMemoryError: Java heap space
 [InputHandler-fz4g25572cg2ztdlfbuknfong7e45wooaidkm3necakz46a6pgicrayd.onion:9999] WARN  b.n.p.n.Connection: Unknown reason for exception at socket: TorSocket[addr=fz4g25572cg2ztdlfbuknfong7e45wooaidkm3necakz46a6pgicrayd.onion,port=9999, localPort=0]
	peer=Optional[fz4g25572cg2ztdlfbuknfong7e45wooaidkm3necakz46a6pgicrayd.onion:9999]
	Exception=java.lang.OutOfMemoryError: Java heap space
 [pool-94-thread-1] ERROR b.n.p.n.ProtoOutputStream: Failed to write envelope java.net.SocketException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3062)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flush(CodedOutputStream.java:2974)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:96)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelopeOrThrow(ProtoOutputStream.java:63)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:46)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.lambda$writeEnvelope$0(SynchronizedProtoOutputStream.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
 [Connection:SendCloseConnectionMessage-52405831-9b7d-46e2-8859-e7f301fe65b9] ERROR b.n.p.n.SynchronizedProtoOutputStream: Failed to write envelope. ExecutionException java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope 
 [Thread-12] INFO  b.n.p.n.TorNetworkNode: Tor shut down completed 
 [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown of node Optional
 [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown completed with all connections  
 [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed 
 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing DaoStateStore took 284  
 [Write-DaoStateStore_to-disk] ERROR b.c.s.CommonSetup: Uncaught Exception from thread to-disk 
 [Write-DaoStateStore_to-disk] ERROR b.c.s.CommonSetup: throwableMessage= Java heap space 
 [Write-DaoStateStore_to-disk] ERROR b.c.s.CommonSetup: throwableClass= class java.lang. 
 [Write-DaoStateStore_to-disk] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.OutOfMemoryError: Java heap space
 
```

**Comment by ripcurlx** [comment]
Could you please try to increase the max memory consumption set to 4 GB right now to a bigger value? See https://bisq.wiki/Reducing_memory_usage.

**Comment by ghubstan** [comment]
This problem may be related to one that was blocking work on atomic-tx, and fixed in https://github.com/bisq-network/bisq/pull/5528 (but not in v1.6.5).  
Raising the MAXRam limit might not solve this.

The problem may be in https://github.com/bisq-network/bisq/blob/release/v1.6.5/core/src/main/java/bisq/core/provider/fee/FeeService.java LINES 140-144

	public void requestFees(@Nullable Runnable resultHandler, @Nullable FaultHandler faultHandler) {
		if (feeProvider.getHttpClient().hasPendingRequest()) {
			log.warn("We have a pending request open. We ignore that request. httpClient {}", feeProvider.getHttpClient());
			                       // Should be: "... We ignore this new request ..."
			return;
		}
		...
	}       
	 
New fee requests are ignored and some pending request callbacks never complete;  this may be why shutdown is hanging.  

@sqrrm's PR may solve this problem too.  It adds a new callback for each new request if there is already pending request, rather than just ignoring the new request and returning.  Then, on success or failure of any callback, all other pending callbacks' respective resultHandlers or faultHandlers are run.  This unwinding of callbacks' handlers might prevent hanging shutdown, but not sure about the OOME.  @sqrrm, is this an incorrect interpretation of https://github.com/bisq-network/bisq/pull/5528?

**Comment by sqrrm** [comment]
There might be some memory leak that has been fixed in #5528 but I doubt there would be a big enough leak to cause OOME. The issue here seems that it's out of memory and I don't see a cause for it, could just be very low memory allocated or some leak.

**Comment by bisqubutor** [comment]
still experienced this errors with v1.7.0 while dao sync was in proggress

![heap](https://user-images.githubusercontent.com/79169291/123734757-76336480-d88d-11eb-9cbb-6b1eaad60cf5.png)
![quithang](https://user-images.githubusercontent.com/79169291/123734768-792e5500-d88d-11eb-90ca-ffdd7e414bfe.png)

```

[Thread-9] INFO  b.c.a.BisqExecutable: Start graceful shutDown 
[Thread-9] INFO  b.c.a.BisqExecutable: OpenOfferManager shutdown started 
[Thread-9] INFO  b.c.o.OpenOfferManager: Remove open offers at shutDown. Number of open offers: 0 
[Thread-9] INFO  b.c.a.BisqExecutable: OpenOfferManager shutdown completed 
[Thread-9] INFO  b.c.b.s.WalletsSetup: walletConfig shutDown started 
[ STOPPING] INFO  b.c.b.s.WalletConfig: BtcWallet saved to file 
[ STOPPING] INFO  b.c.b.s.WalletConfig: BsqWallet saved to file 
[ STOPPING] INFO  b.c.b.s.WalletConfig: SPV file closed 
[ STOPPING] INFO  o.b.c.PeerGroup: Awaiting PeerGroup shutdown ... 
[PeerGroup Thread] INFO  o.b.c.PeerGroup: Stopping ... 
[PeerGroup Thread] ERROR o.b.c.PeerGroup: Exception when shutting down java.lang.IllegalStateException: Expected the service NioClientManager [FAILED] to be TERMINATED, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:329)
	at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitTerminated(AbstractExecutionThreadService.java:223)
	at org.bitcoinj.core.PeerGroup$10.run(PeerGroup.java:1155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

[ STOPPING] INFO  o.b.c.PeerGroup: ... took 1.434 ms 
[ STOPPING] INFO  b.c.b.s.WalletConfig: PeerGroup stopped 
[Thread-9] INFO  b.c.b.s.WalletsSetup: walletConfig shutDown completed 
[Thread-9] INFO  b.c.a.BisqExecutable: WalletsSetup shutdown completed 
[pool-163-thread-1] ERROR b.n.p.n.ProtoOutputStream: Failed to write envelope java.net.SocketException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3062)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flushIfNotAvailable(CodedOutputStream.java:3057)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeInt32(CodedOutputStream.java:2726)
	at protobuf.RefreshOfferMessage.writeTo(RefreshOfferMessage.java:170)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
	at protobuf.NetworkEnvelope.writeTo(NetworkEnvelope.java:2528)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:95)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelopeOrThrow(ProtoOutputStream.java:63)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:46)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.lambda$writeEnvelope$0(SynchronizedProtoOutputStream.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

[JavaFX Application Thread] INFO  b.n.p.n.TorNetworkNode: Tor has been created already so we can shut it down. 
[InputHandler-wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000] INFO  b.c.d.n.m.GetBlocksResponse: Received a GetBlocksResponse with 1480 blocks and 1762.895 kB size 
[JavaFX Application Thread] ERROR b.n.p.n.TorNetworkNode: Shutdown torNetworkNode failed with exception: We did not receive a response within one minute of waiting. 
[JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown 6 connections 
[JavaFX Application Thread] INFO  b.c.ClockWatcher: We have been in standby mode for 119 sec 
[JavaFX Application Thread] WARN  b.c.a.BisqExecutable: Graceful shut down not completed in 20 sec. We trigger our timeout handler. 
[JavaFX Application Thread] ERROR b.n.p.n.TorNetworkNode: A timeout occurred at shutDown 
[JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed 
[JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
[JavaFX Application Thread] WARN  b.c.p.PersistenceManager: We got flushAllDataToDisk called again. This can happen in some rare cases. We ignore the repeated call. 
[JavaFX Application Thread] WARN  b.n.p.n.TorNetworkNode: We got called shutDown again and ignore it. 
[JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown of node Optional[wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000] completed 
[JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown completed with all connections closed 
[JavaFX Application Thread] INFO  b.c.p.PersistenceManager: flushAllDataToDisk completed 
[JavaFX Application Thread] INFO  b.c.a.BisqExecutable: Graceful shutdown resulted in a timeout. Exiting now. 

```

**Comment by ripcurlx** [comment]
> still experienced this errors with v1.7.0 while dao sync was in proggress
> 
> ![heap](https://user-images.githubusercontent.com/79169291/123734757-76336480-d88d-11eb-9cbb-6b1eaad60cf5.png)
> ![quithang](https://user-images.githubusercontent.com/79169291/123734768-792e5500-d88d-11eb-90ca-ffdd7e414bfe.png)
> 
> ```
> 
> [Thread-9] INFO  b.c.a.BisqExecutable: Start graceful shutDown 
> [Thread-9] INFO  b.c.a.BisqExecutable: OpenOfferManager shutdown started 
> [Thread-9] INFO  b.c.o.OpenOfferManager: Remove open offers at shutDown. Number of open offers: 0 
> [Thread-9] INFO  b.c.a.BisqExecutable: OpenOfferManager shutdown completed 
> [Thread-9] INFO  b.c.b.s.WalletsSetup: walletConfig shutDown started 
> [ STOPPING] INFO  b.c.b.s.WalletConfig: BtcWallet saved to file 
> [ STOPPING] INFO  b.c.b.s.WalletConfig: BsqWallet saved to file 
> [ STOPPING] INFO  b.c.b.s.WalletConfig: SPV file closed 
> [ STOPPING] INFO  o.b.c.PeerGroup: Awaiting PeerGroup shutdown ... 
> [PeerGroup Thread] INFO  o.b.c.PeerGroup: Stopping ... 
> [PeerGroup Thread] ERROR o.b.c.PeerGroup: Exception when shutting down java.lang.IllegalStateException: Expected the service NioClientManager [FAILED] to be TERMINATED, but the service has FAILED
> 	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
> 	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:329)
> 	at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitTerminated(AbstractExecutionThreadService.java:223)
> 	at org.bitcoinj.core.PeerGroup$10.run(PeerGroup.java:1155)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
> 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 
> [ STOPPING] INFO  o.b.c.PeerGroup: ... took 1.434 ms 
> [ STOPPING] INFO  b.c.b.s.WalletConfig: PeerGroup stopped 
> [Thread-9] INFO  b.c.b.s.WalletsSetup: walletConfig shutDown completed 
> [Thread-9] INFO  b.c.a.BisqExecutable: WalletsSetup shutdown completed 
> [pool-163-thread-1] ERROR b.n.p.n.ProtoOutputStream: Failed to write envelope java.net.SocketException: An established connection was aborted by the software in your host machine
> 	at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
> 	at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
> 	at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
> 	at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
> 	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3062)
> 	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flushIfNotAvailable(CodedOutputStream.java:3057)
> 	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeInt32(CodedOutputStream.java:2726)
> 	at protobuf.RefreshOfferMessage.writeTo(RefreshOfferMessage.java:170)
> 	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
> 	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
> 	at protobuf.NetworkEnvelope.writeTo(NetworkEnvelope.java:2528)
> 	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:95)
> 	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelopeOrThrow(ProtoOutputStream.java:63)
> 	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:46)
> 	at bisq.network.p2p.network.SynchronizedProtoOutputStream.lambda$writeEnvelope$0(SynchronizedProtoOutputStream.java:47)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 
> [JavaFX Application Thread] INFO  b.n.p.n.TorNetworkNode: Tor has been created already so we can shut it down. 
> [InputHandler-wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000] INFO  b.c.d.n.m.GetBlocksResponse: Received a GetBlocksResponse with 1480 blocks and 1762.895 kB size 
> [JavaFX Application Thread] ERROR b.n.p.n.TorNetworkNode: Shutdown torNetworkNode failed with exception: We did not receive a response within one minute of waiting. 
> [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown 6 connections 
> [JavaFX Application Thread] INFO  b.c.ClockWatcher: We have been in standby mode for 119 sec 
> [JavaFX Application Thread] WARN  b.c.a.BisqExecutable: Graceful shut down not completed in 20 sec. We trigger our timeout handler. 
> [JavaFX Application Thread] ERROR b.n.p.n.TorNetworkNode: A timeout occurred at shutDown 
> [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: P2PService shutdown completed 
> [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
> [JavaFX Application Thread] WARN  b.c.p.PersistenceManager: We got flushAllDataToDisk called again. This can happen in some rare cases. We ignore the repeated call. 
> [JavaFX Application Thread] WARN  b.n.p.n.TorNetworkNode: We got called shutDown again and ignore it. 
> [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown of node Optional[wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000] completed 
> [JavaFX Application Thread] INFO  b.n.p.n.NetworkNode: Shutdown completed with all connections closed 
> [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: flushAllDataToDisk completed 
> [JavaFX Application Thread] INFO  b.c.a.BisqExecutable: Graceful shutdown resulted in a timeout. Exiting now. 
> ```

Could you try to allocate more RAM to see if this prevents the Java heap space issue? https://bisq.wiki/Reducing_memory_usage

I haven't changed the default configuration for this release already as I wanted to get more data on different config results and do some memory profiling in case we introduced some memory leak in one of the last versions.

**Comment by bisqubutor** [comment]
yes, i have `java-options=-XX:MaxRAM=4g`

**Comment by ripcurlx** [comment]
> yes, i have `java-options=-XX:MaxRAM=4g` i remember i increased it, but seems my bisq.cfg got overwritten by upgrade of version

Would be interesting if a certain max ram value fixes it, so we can apply it as a default for the upcoming versions.

**Comment by pazza83** [comment]
@ripcurlx I have not had a java heap error since I increase the `java-options=-XX:MaxRAM=4g` in the bisq.cfg to` java-options=-XX:MaxRAM=32g`
