### ISSUE TITLE
Trades volume graphic is wrong

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#559]
Hi,

Look the screenshots to understand the problem. 

![captura de tela de 2016-07-30 22-24-39](https://cloud.githubusercontent.com/assets/1178856/17274079/7f1681a0-56a5-11e6-857b-d84c30686fbc.png)

![captura de tela de 2016-07-30 22-25-21](https://cloud.githubusercontent.com/assets/1178856/17274081/886b21ca-56a5-11e6-90ac-565e459c5509.png)

**Comment by bitcoinuser** [comment]
Just to clarify:

The volume that appear on popup, doesn't correspond with the real volume on the specific date.

**Comment by ManfredKarrer** [comment]
That happends just a the change of the day. the 0.2 is for the 31. But is a bug in syncing not correctly when the chart moves one tick (day in that case).

**Comment by haiqu** [comment]
Yeah, it's out by one position relative to the text in the x-axis. I took a look but couldn't find a way to fix this easily.

**Comment by ManfredKarrer** [comment]
I think it goes back 24 hours instead of a calendar date....

**Comment by haiqu** [comment]
Same on every scale. If Month is selected, it's out by one month. It's just an alignment issue.

**Comment by ManfredKarrer** [comment]
For me not, But maybe its a time zone issue. Anyway would be good if it would use calendar day instead of time span (not sure whats standard in other exchanges).

**Comment by haiqu** [comment]
Fixed in v0.4.9.7 ... please close.

**Comment by ManfredKarrer** [comment]
It is not really fixed. I looked into it but it requires a bit more effort to fix that.

**Comment by ManfredKarrer** [comment]
https://github.com/bisq-network/exchange/issues/881

**Comment by sqrrm** [comment]
There are a few issues at play here. While collecting the data the time is counted backwards from current time and split into time slices, showing the last 30 slices. For days this happens to work out correctly but for longer time spans it counts a number of days backwards from the current day, causing misaligned months and years for example.

The reported issue is due to the table view showing time in local time but the diagram is always calculated in UTC. I think it would be reasonable to always show UTC time for trades in both the table and the chart since bisq is a global exchange and there is no better common measure for time.

For the other time spans I'll make it group trades by calendar weeks/months/years and hours per clock hour. For the 10 minute and shorter ticks, are they really valuable time spans for an exchange where trades take significantly longer to complete?

**Comment by ManfredKarrer** [comment]
@sqrrm I am not sure about the analysis regarding UTC. Date is always treated locally, so it should not matter. If user A has traded at 16:00 local time and has timezone -3 (trade happened at 19:00 UTC 0) and user B has timezone +2 he will see user A's trade date with his local date of 21:00.

The app treats time always local with OS clocks timezone.

The other issues you brought up I can confirm. I have not looked so much how other charts solve those issues (going back 1 week vs. using a grid of calendar weeks). Removing the 10 min interval is ok for me if it helps.

**Comment by sqrrm** [comment]
@ManfredKarrer java.util.Date keeps the time as `long` number of ms since beginning of time. When we do the day to tick conversion `TimeUnit.MILLISECONDS.toDays()` does `time_ms / 86400000L`. This means the tick for days will always align with UTC (apart perhaps from leap seconds and such, I will ignore that for now).

The displayed date in the trade table will use local time zone however.

In your example the trade A on day 1 UTC will still be represented by the same `long` in all time zones and be assigned to day 1 no matter which time zone the user is in. The displayed time for that trade in the table view will be in local time and some user C in UTC +6 will see it as traded at local time 01:00 during day 2, which is what will show in the table view.

It's quite possible I've misunderstood something, but I believe this is how it's currently working.

It's probably not much more work to keep the 10 minute tick, i just thought it was a bit short for this kind of exchange. Will keep it.

**Comment by sqrrm** [comment]
PR at https://github.com/bisq-network/exchange/pull/986

**Comment by ManfredKarrer** [comment]
Merged.
