### ISSUE TITLE
Bitsquare tries to connect to IPv4 ports 8333, although "Use Tor for Bitcoin network" is enabled

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#756]
Bitsquare 0.4.9.9 on Debian 8("Jessie") x86_64

"Use Tor for Bitcoin network" is enabled.

No custom Bitcoin node is configured.

The host where Bitsquare is runnin on, has outgoing firewall restrictions.
Only the following is allowed outgoing:

TCP ports 80,443,6667,9001,9030
9050 (Tor socks5-Proxy on another host in LAN, used as proxy in Bitcoin Core)

UDP port 53 (DNS)

ICMP

In the firewall log I see many drops all the time of TCP packets from Bitsquare with destination IPv4 addresses on the internet and destination TCP port 8333.

I guess, since it says "Use Tor" and not "Prefer Tor", there should not be any IPv4 clearnet requests to Bitcoin nodes.

I checked two of the tried IPv4 addresses on http://torstatus.blutmagie.de/index.php and they are not listed there, so they are no Tor nodes.

**Comment by ghost** [comment]
When starting Bitsquare with command line parameter

`--socks5DiscoverMode ONION`

there are no connection attempts to IPv4 TCP ports 8333 anymore (currently).

Edit: ca. 15 min after startup the Bitcoin connection to 127.0.0.1:8333 got lost("Bitcoin network peers: 0") and the TCP port 8333 connection attempts start again.

**Comment by dan-da** [comment]
thx for the report.  I will have a look.

**Comment by dan-da** [comment]
so far I have not been able to reproduce the outgoing dropped packets on port 8333.

Here is what I did:

```
sudo ufw enable
sudo ufw default deny outgoing
sudo ufw allow out 443/tcp
sudo ufw allow out 9001/tcp
sudo ufw allow out 9030/tcp

$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
9001/tcp                   ALLOW OUT   Anywhere                  
9030/tcp                   ALLOW OUT   Anywhere                  
443                        ALLOW OUT   Anywhere                  
9001/tcp (v6)              ALLOW OUT   Anywhere (v6)             
9030/tcp (v6)              ALLOW OUT   Anywhere (v6)             
443 (v6)                   ALLOW OUT   Anywhere (v6)
```

( at this point, I verified that I cannot ping or load a website on port 80, etc. )
```
tail -f /var/log/ufw.log
```

With this configuration, bitsquare is able to connect to the p2p network and the bitcoin network.  It finds both ipv4 and .onion peers.  I did not use --socks5DiscoverMode arg, so that is default behavior.

I do not see any BLOCK messages in ufw.log that uses port 8333, or for an address that appears in the connected peers settings.  Also I did not see any BLOCK log lines appear during bitsquare startup.

I then repeated with --socks5DiscoverMode ONION, with same/similar results.
I then repeated with --socks5DiscoverMode DNS, with same/similar results.
I then repeated with --socks5DiscoverMode ADDR, with same/similar results.

@wodry it is unclear to me what may be happening in your environment.  My first guess would be that the 8333 connection attempts are coming from another process, eg a bitcoin wallet.  Are you certain that the blocked packets you are seeing to port 8333 come from bitsquare and not another process?   I don't know what firewall software you are using, but at least in ufw there does not seem to be any way to view the process id in the log.   If you are certain, can you please provide the exact methodology you use to setup the firewall and log and identify the packet's source process, so that I can try it?

Also, do you see any problem with my testing methodology, or have other ideas?

**Comment by dan-da** [comment]
> 15 min after startup the Bitcoin connection to 127.0.0.1:8333 got lost("Bitcoin network peers: 0") and the TCP port 8333 connection attempts start again.

@wodry how/why is bitsquare connecting to 127.0.0.1?    I guess you are using --useLocalhost or --seedNodes.  Can you please specify full set of startup flags?

@ManfredKarrer maybe this is somehow related to connecting with localhost.  I have not tested with that type of configuration...

**Comment by ghost** [comment]
Thanks for checking.
I added ICMP and TCP 9050 to firewall rule info in my OP above, these were missing.

When I first had the problem with no Bittcoin peer connection, I started Bitsquare as with version 0.4.9.8, without any command line parameter. Then I tested with "--socks5DiscoverMode ONION" and thought at first, that would have helped, but it turned out after 15 min, it did not change anything, see my second post.
Now I am running again without any command line parameters, just plain "/opt/Bitsquare/Bitsquare".
And here the GUI setting. Please be noticed, that there is a Bitcoin connection now, since I have _enabled TCP port 8333 in firewall_, I will come back to that later:

![matrica](https://cloud.githubusercontent.com/assets/8447873/22915193/b66a160a-f275-11e6-898a-2236873eb385.png)

I want to point out, that P2P-Connection has _no_ problem, all fine connection to .onion addresses, both inbound and outbound. I also did not change anything else in the last weeks aside of the Bitsquare version.

Problem is only, that I do not get no Bitcoin connection since version 0.4.9.9, when blocking outgoing TCP 8333.

I use iptables on the Gateway Host. The whole iptables configuration would be too long for this topic and I do not want to post it here, but the main regarding rules for forwarding from the Bitsqaure DMZ host 192.168.9.10 are these:
```
*filter
:FORWARD DROP [0:0]                     (drop all forwarding by default)
# Allow always ACK but not SYN ACK
-A FORWARD -p tcp -m tcp --tcp-flags SYN,ACK ACK -j ACCEPT
# Forward established connections
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED,UNTRACKED -j ACCEPT
# allow ICMP
--append FORWARD --in-interface br1 -o eno1 --source 192.168.9.10 --protocol icmp --jump ACCEPT
#-A FORWARD --in-interface br1 -o eno1 --jump ACCEPT
# allow nes DNS connections
--append FORWARD --in-interface br1 -o eno1 --source 192.168.9.10 --protocol udp -m multiport --dports 53 --jump ACCEPT
# allow http, https, irc, bitcoin, Tor, Tor Dir
--append FORWARD --in-interface br1 -o eno1 --source 192.168.9.10 --protocol tcp -m multiport --dports 80,443,6667,8333,9001,9030 --jump ACCEPT
# log all from br1 that get dropped now:
-A FORWARD --in-interface br1 --jump LOG --log-prefix "ipt-FORWARD-from-br1-DROP: "
```

You are right, I cannot see the source process of the dropped packets in the drop log. But I am pretty sure that they come only from Bitsquare, because when I change the above iptables rule to the following (all the same as above, but without port 8333):
```
--append FORWARD --in-interface br1 -o eno1 --source 192.168.9.10 --protocol tcp -m multiport --dports 80,443,6667,9001,9030 --jump ACCEP
```
(which was the setting I run all the time with 0.4.9.8), then the 8333 packets start being logged, and bitcoin connection is lost. At once, when I enable the rule and allow 8333 again, Bitcoin connection is established. That is the reason, that I have allowed it now, to have a Bitcoin connection.

**Comment by ghost** [comment]
> I do not see any BLOCK messages in ufw.log that uses port 8333

I do not know ufw, but did You check that You see block message if You try to connect manually, e.g. with
`telnet 1.2.3.4 8333`
(where 1.2.3.4 is the IPv4 address of a Bitcoin node in the internet You know running)
That command should time out and lead to a block message.

**Comment by ghost** [comment]
I changed the firewall rule like mentioned above, disabling port 8333. Bitsqure kept running without Bitcoin connection lost and drop logs for 10 minutes. Then I stopped Bitsquare and started it again. Now, directly after startup, the drops are logged (no drop logs for 8333 in the last hours before), here three examples:
```
Feb 14 05:49:13 xxx kernel: [2351698.887076] ipt-FORWARD-from-br1-DROP: IN=br1 OUT=eno1  MAC=xxx SRC=192.168.9.10 DST=80.223.134.5 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=8822 DF PROTO=TCP SPT=53377 DPT=8333 WINDOW=29200 RES=0x00 SYN URGP=0 
Feb 14 05:52:01 xxx kernel: [2351867.257037] ipt-FORWARD-from-br1-DROP: IN=br1 OUT=eno1 MAC=xxx SRC=192.168.9.10 DST=47.17.59.108 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=22847 DF PROTO=TCP SPT=49241 DPT=8333 WINDOW=29200 RES=0x00 SYN URGP=0 
Feb 14 05:52:02 xxx kernel: [2351868.217074] ipt-FORWARD-from-br1-DROP: IN=br1 OUT=eno1 MAC=xxx SRC=192.168.9.10 DST=192.99.224.132 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=58689 DF PROTO=TCP SPT=44336 DPT=8333 WINDOW=29200 RES=0x00 SYN URGP=0
```
And no connection to Bitcoin network anymore, while P2P-Connections are fine:
![matrica](https://cloud.githubusercontent.com/assets/8447873/22915824/552085e6-f27a-11e6-8ed7-d5e1f0decabd.png)

As soon as I enable 8333 in firewall again, Bitcoin connection gets established and the drop logs stop.

**Comment by ghost** [comment]
It looks to me, that the checkmark at "Use Tor for Bitcoin network" is wrong, and really Tor is _not_ used for Bitcoin network.

An explanation could be the following (brainstorming):
- on startup, Bitsquare detects Bitcoin Core running on localhost
- Due to the feature introduced in 0.4.9.9 "Connect to local Bitcoin Core node if it is running (ignore use Tor flag)", Tor usage for Bitcoin network is disabled.
- Bitsquare tries to connect to Bitcoin Core on localhost, but fails (maybe because Bitcoin Core is running in onlynet=onion mode? or for other reasons)
- Bitsquare goes on trying to connect to external Bitcoin nodes, but Tor usage remains disabled, and the checkmark in the GUI is wrong

**Comment by dan-da** [comment]
@wodry, yes I think this theory is correct or at least in the right direction, ie it is related to use of bitcoind on localhost. 

It is best that @ManfredKarrer comment/review, as he introduced that functionality.

However, I made one change to bitcoinj that is likely relevant.  In older versions bitcoinj would only connect to peers that it finds during the initial discovery process. (In clearnet mode, these are peers from DNS. In tor mode, it is ipv4 peers that are hard-coded.)   The relevant change in 0.4.9.9 is that bitcoinj will listen to addr messages from peers and attempt connections to new peers until it reaches the target of 10.  This then could cause the connection attempts that you see.  

So, it seems that the "Connect to local Bitcoin Core" setting disables tor mode for the bitcoin network, perhaps expecting that bitcoind on localhost will be the only peer.  Except then bitcoinj listens for new peers advertised by local bitcoind and attempts connections, over clearnet.

It is also possible that built-in seed peers are being contacted in this mode, which they shouldn't be.  That is another thing to check.

I think the simplest correct fix in a future release would be to disable adding new peers from addr messages when using localhost bitcoind.  or make it optional.  And verify that none of the regular discovery modes are used either.

@wodry In the meantime, for the 0.4.9.9 release, it seems that if you wish privacy on the bitcoin network it is best to either avoid use of localhost bitcoind, or block outgoing 8333 connections, as you have done.

**Comment by ManfredKarrer** [comment]
@dan-da Re "how/why is bitsquare connecting to 127.0.0.1": When u run a local Bitcoin Core node it connects to localhost and ignores tor setting. I just added that before the release. So running a local BTC node is the best protection against spying "chainanalysis" nodes who abuse the broken BitcoinJ Bloom filters to get out the information which addresses are owned by one Bitsquare peer (thought over Tor they at least don't get the IP address).

**Comment by ManfredKarrer** [comment]
@dan-da Re: "@wodry In the meantime, for the 0.4.9.9 release, it seems that if you wish privacy on the bitcoin network it is best to either avoid use of localhost bitcoind, or block outgoing 8333 connections, as you have done."

As said in the above comment the best privacy protection is to run a localhost Bitcoin node. If for some reason it starts to connect to other nodes we have a bug (or need to add more checks to not add new nodes). There might be issues also after connection lost, not sure how it behaves in the "use Tor" mode when a localhost btc nodes is connected but lost connection after some time.
I think as far i remember the "non tor" mode worked correctly to re-connect to the public btc network but only to 1 peer (which is also not ok) but the "tor enabled" mode did not connect at all.
I dont see high prio in fixing that as it should not happen that u lose connection to localhost, but if anyone want to look into that and fix it would be good to have as well...

**Comment by ghost** [comment]
When I disable "Use Tor for Bitcoin network" (uncheck) and block outgoing TCP port 8333, the behaviour is the same: No connection to localhost Bitcoin Node, and no connection to external Bitcoin nodes, but drops in firewall log for TCP port 8333.

Whe I disable "Use Tor for Bitcoin network" (uncheck) and allow outgoing TCP port 8333, Bitsquare connects to one Bitcoin node in the internet, and I see drops of TCP packets to port 53 in the log, that I have not seen before.

So, the behaviour is the same, regardless of toggle "Use Tor for Bitcoin network" switched on or off: No connection to local Bitcoin Node, and connection to external Bitcoin nodes only in clearnet.

**Comment by ghost** [comment]
When I disable "Use Tor for Bitcoin network" (uncheck) and allow outgoing TCP port 8333 and _set "Use custom Bitcoin network peers" to "127.0.0.1"_ then I can reproduce the failing connection attempts to local Bitcoin Node every second. I can see them in the Bicoin Core debug log.

**Comment by ghost** [comment]
When I enable "Use Tor for Bitcoin network" (check) and block outgoing TCP port 8333, and _shutdown the Bitcoin Core on localhost_ and start Bitsquare, it connects to ten addresses, mixed .onion and [IPv4]:8333 in Bitcoin network, so that's Tor traffic.

So, the existence of a running Bitcoin Core node (in my case version 0.13.2) on localhost disturbes the Bitcoin network connections.

**Comment by dan-da** [comment]
I will try and take a look when I get some free time.  Hopefully I can disable the bitcoinj addr listening when localhost is only peer.  that's a starting point at least.

**Comment by dan-da** [comment]
commit 30e91ea0ee1f7640a79c7eb1c4ae7636cd4165cd disables adding new nodes from the network when any list of nodes is provided by user.

@ManfredKarrer can you confirm that this also applies when --useLocalhost is used?

**Comment by ManfredKarrer** [comment]
@dan-da --useLocalhost is only for the P2P network connection. But I will rename that to make it more explicit. I will check again if localHost is nadled correctly. Probably there is something missing. Thanks for pointing out!

**Comment by ManfredKarrer** [comment]
Yes was missing inside BitcoinJ. I added it as the APIs are not public to request the state from outside.
https://github.com/bitsquare/bitcoinj/commit/67628b0ae89be1ffeb1acf09a2b05395190126c5

**Comment by dan-da** [comment]
good catch.   I was unaware of the UseLocalhostPeerWhenPossible setting in bitcoinj.  seems like correct fix.

**Comment by ghost** [comment]
With 0.4.9.9.1 and "Use Tor for Bitcoin network" enabled, I did not see any connection attempts to IPv4 TCP 8333 anymore. So, this particular issue seems to be solved in 0.4.9.9.1, the other issues remain.

**Comment by ManfredKarrer** [comment]
Thanks for testing!
@dan-da: If you have time, could you have a look?

**Comment by dan-da** [comment]
@ManfredKarrer : @wodry is saying this issue is resolved for him.  So it can be closed.

**Comment by ManfredKarrer** [comment]
@wodry: Do you refer with "the other issues remain." to the other GH issue or to anything above in that issue? I delegated that topic mostly to @dan-da so forgive that I am not very up-to date here...

**Comment by ghost** [comment]
Issue mentioned in the topic seems to be solved at a first look, closing.

For the other issues, see https://github.com/bitsquare/bitsquare/issues/758
