### ISSUE TITLE
Remove ShadowCash and Add Particl

### ISSUE THREAD

**Issue by dasource** [bisq-network/bisq#911]
Hi,

As you may be aware ShadowCash no longer is developed and a new project Particl did a 1:1 conversion from SDC:PART.

As such it would make sense to remove SDC and add PART
Can you please advise what the process should be?

Thanks
Shazzy

**Comment by ManfredKarrer** [comment]
Done.

**Comment by imybb** [comment]
Hey guys,
I just downloaded your latest version and I can still see ShadowCash (SDC) rather than Particl (PART).
Could you please advise when this will be changed, Thank you.
![bisq_sdc](https://user-images.githubusercontent.com/30150617/32617929-3b25a6a4-c56e-11e7-893a-fdacfc0c4a52.png)

**Comment by cbeams** [comment]
IIRC, @ManfredKarrer, $PART is being removed in 0.6 as an unused token, correct? Is it possible that it was never actually listed in the first place?

**Comment by ManfredKarrer** [comment]
Yes ShadowCash (Particle) was never traded and has never done a PR for address validation so it got removed in the next version.  If you want to get it added deliver a PR for address validation.

**Comment by cbeams** [comment]
I just tweeted a heads-up to the team at https://twitter.com/bisq_network/status/928908774076768256. Particl folks, if you do want to stay listed, please follow the instructions at https://github.com/bisq-network/docs/blob/master/exchange/howto/list-token.adoc, thanks!

**Comment by imybb** [comment]
@cbeams @ManfredKarrer we will submit a new PR as per your instructions

**Comment by ManfredKarrer** [comment]
@imybb cool! We will release soon, so would need it before Monday to make it into the release.

**Comment by rynomster** [comment]
Hi Guys, added #1007

**Comment by ManfredKarrer** [comment]
Cool. will check later...
